#!/bin/bash

#usage:
#	$ gcm "my commit message"

# defaults:
#	commit message: did something

msg=${1:-did something}

echo "Staging the following modifications:"
git status

read  -p "Stage the above modifications and commit? [y/n]    " doCommit

if [ "$doCommit" == "y" ]
then
	git add .
	git commit -m "$msg"
fi

