#!/bin/bash

#usage:
#	$ qpush ["my commit message"] [remote] [branch]

# defaults:
#	commit message: quick commit
#	remote: origin
#	branch: current branch
#		- if you do not have a current branch (ex. you've just added the remote), will fail to push


#get current branch
currentBranch=$(git branch | grep ^'*' | cut -d ' ' -f 2)

msg=${1:-quick commit}
remote=${2:-origin}

echo ""
echo "Staging the following modifications:"
git status

echo ""
read  -p "Stage the above modifications, commit, and push to remote $remote, branch $currentBranch ? [y/n]    " doCommit

if [ "$doCommit" == "y" ]
then
	git add .
	git commit -m "[q] $msg"
	git push $remote $branch
fi
